module.exports = {
  QIC_ASSISTANT_ID: 'QIC_ASSISTANT_ID',
  QIC_AWS_REGION: 'QIC_AWS_REGION',
  QIC_AWS_ACCESS_KEY_ID: 'QIC_AWS_ACCESS_KEY_ID',
  QIC_AWS_SECRET_ACCESS_KEY: 'QIC_AWS_SECRET_ACCESS_KEY',
  QIC_CLIENT_TOKEN: 'QIC_CLIENT_TOKEN',
  QIC_GENERATE_FILLER_MESSAGE: 'QIC_GENERATE_FILLER_MESSAGE'
}
